# -*- coding: utf-8 -*-
"""AutoContactBook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LeezFNGzm8AmUVy5EUOfb6S6Qxr5Hbtp
"""

import sqlite3
from rich.console import Console
from rich.table import Table

# تنظیم پایگاه داده SQLite
conn = sqlite3.connect("contacts.db")
cursor = conn.cursor()
cursor.execute("""
CREATE TABLE IF NOT EXISTS contacts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    email TEXT,
    phone TEXT
)
""")
conn.commit()

# توابع کمکی
def add_contact(name, email, phone):
    cursor.execute("INSERT INTO contacts (name, email, phone) VALUES (?, ?, ?)", (name, email, phone))
    conn.commit()

def search_contact(query):
    cursor.execute("SELECT * FROM contacts WHERE name LIKE ? OR phone LIKE ?", (f"%{query}%", f"%{query}%"))
    return cursor.fetchall()

def display_contacts():
    cursor.execute("SELECT * FROM contacts")
    contacts = cursor.fetchall()
    table = Table(title="لیست مخاطبین")
    table.add_column("شناسه", justify="right")
    table.add_column("نام", justify="left")
    table.add_column("ایمیل", justify="left")
    table.add_column("تلفن", justify="left")
    for contact in contacts:
        table.add_row(str(contact[0]), contact[1], contact[2], contact[3])
    console = Console()
    console.print(table)

# رابط کاربری متنی (TUI)
console = Console()
console.print("[bold green]به اپلیکیشن کتابچه تماس خوش آمدید![/bold green]")

while True:
    console.print("\n[cyan]گزینه‌ها:[/cyan]\n1. افزودن مخاطب\n2. جستجوی مخاطب\n3. نمایش همه مخاطبین\n4. خروج")
    choice = console.input("گزینه موردنظر را وارد کنید: ")

    if choice == "1":
        name = console.input("نام: ")
        email = console.input("ایمیل: ")
        phone = console.input("تلفن: ")
        add_contact(name, email, phone)
        console.print("[bold green]مخاطب با موفقیت اضافه شد![/bold green]")

    elif choice == "2":
        query = console.input("جستجو: ")
        results = search_contact(query)
        if results:
            for result in results:
                console.print(f"[yellow]شناسه: {result[0]}[/yellow] | نام: {result[1]} | ایمیل: {result[2]} | تلفن: {result[3]}")
        else:
            console.print("[red]مخاطبی یافت نشد![/red]")

    elif choice == "3":
        display_contacts()

    elif choice == "4":
        console.print("[bold green]خداحافظ![/bold green]")
        break

    else:
        console.print("[red]گزینه نامعتبر، دوباره امتحان کنید![/red]")